<nav>
  <div class="nav-wrapper">
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="left">
      <li><a href="index.php">Home</a></li>
    </ul>
    <ul class="right hide-on-med-and-down">
      <li><a href="vivian.php">Vivian</a></li>
      <li><a href="gayeon.php">Gayeon</a></li>
      <li><a href="ben.php">Ben</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="vivian.php">Vivian</a></li>
      <li><a href="gayeon.php">Gayeon</a></li>
      <li><a href="ben.php">Ben</a></li>
    </ul>
  </div>
</nav>
